version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-init/postgres:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  exoquic-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exoquic-agent
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - EXOQUIC_ENDPOINT=https://api.exoquic.com/v1/data
      - EXOQUIC_API_KEY=your-api-key-here
    volumes:
      - agent-data:/app/data
      - agent-logs:/app/logs
      - ./config.properties:/app/config.properties

volumes:
  postgres-data:
  agent-data:
  agent-logs:
